### ISSUE TITLE
Support for TLS options (client cert/key, CA, ...)

### ISSUE THREAD

**Issue by breser** [silas/node-papi#11]
papi is using the node https library which supports using custom CAs, client certificates, etc...  But it doesn't provide a way to pass those arguments through.  It'd be nice to be able to use papi to support APIs that require client certificates.

**Comment by silas** [comment]
I believe it supports most options, they're just not documented. You should be able to pass in any of the following: https://github.com/silas/node-papi/blob/36feca54f44f7834f19c55d6f6b4bd97f2929586/lib/constants.js#L53-L63

Did you need any additional options?

**Comment by breser** [comment]
Nope that covers what I wanted.  Closing.
