### ISSUE TITLE
multipart post support

### ISSUE THREAD

**Issue by gaborcsardi** [silas/node-papi#13]
Would be great for file uploads in the Jenkins API.

**Comment by gaborcsardi** [comment]
Looking at the code, this is already possible by setting the content type header and the body manually. Still, multipart is not that easy to do manually, so maybe some helper function would make sense?

This is how request is doing it:
https://github.com/request/request/blob/253c5e507ddb95dd88622087b6387655bd0ff935/lib/multipart.js#L66-L96

**Comment by gaborcsardi** [comment]
Happening here: #15

**Comment by silas** [comment]
Decided against multipart support, see https://github.com/silas/node-papi/pull/15#issuecomment-396463383
