### ISSUE TITLE
TypeError: utf8 is not a function - codecs.encode() is not backward compatible with older Node versions

### ISSUE THREAD

**Issue by kunalmanchekar** [silas/node-papi#16]
https://github.com/silas/node-papi/blob/8c54d6a1cc5b3431ae03fed28761c33d6a9ccee2/lib/codecs.js#L20

I was creating jenkins Node using **https://github.com/silas/node-jenkins** and got to know that it has dependency with **papi** where papi is calling Buffer.from() which was introduced in **Node v6.0.0** and I need to use **Node v4.4.5** in my project.

I was getting error in my response as 
`TypeError: jenkins: node.create: encode (application/x-www-form-urlencoded) failed: utf8 is not a function`

Can you make it compatible by handling `new Buffer(data)` instead of `Buffer.from(data, 'utf8')` where it is not supported?

**Comment by kunalmanchekar** [comment]
I have found solution for this!! I will contribute my solution soon...

**Comment by kunalmanchekar** [comment]
PR raised for this: https://github.com/silas/node-papi/pull/17

**Comment by silas** [comment]
Sorry, I'm not supporting EOL versions of Node.js, see https://github.com/silas/node-papi/pull/17#issuecomment-419297636
