### ISSUE TITLE
marathon.register does not allow specfying headers

### ISSUE THREAD

**Issue by memelet** [silas/node-papi#6]
It seems that marathon requires content-type json even though no data is being posted. But register eats all the papi opts (eg, type)

```
EventSubscription.prototype.register = function(opts, callback) {
  if (typeof opts === 'string') {
    opts = { url: opts };
  }

  var req = {
    name: 'eventSubscription.register',
    path: '/eventSubscriptions',
    query: { callbackUrl: opts.url },
  };

  if (!opts.url) return callback(this.marathon._err('url required', req));

  this.marathon._post(req, utils.empty, callback);
};
```

**Comment by silas** [comment]
I stopped supporting the mesos package a while back and it's not something I can fix here. Sorry for never getting back to you (I never really used the package and it also immediately languished).
