### ISSUE TITLE
GLOBAL is deprecated in node.js 6

### ISSUE THREAD

**Issue by djMax** [silas/node-papi#9]
DeprecationWarning: 'GLOBAL' is deprecated, use 'global'

from tools.js, line 83

```
    if (GLOBAL.Promise) {
      wrapper = fromCallback;
    } else {
      throw new Error('wrapper required');
    }
```

**Comment by silas** [comment]
Thanks for the issue and fix!

Once I get the tests happy with Node v6 I'll do a release.
